// <auto-generated />
using IdealWay.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IdealWay.Persistence.Migrations
{
    [DbContext(typeof(DevSalaryDbContext))]
    [Migration("20191014045713_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IdealWay.Domain.Entities.Developer", b =>
                {
                    b.Property<int>("DeveloperId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("PrimaryLanguageId");

                    b.Property<int>("YearsOfExperience");

                    b.HasKey("DeveloperId");

                    b.HasIndex("PrimaryLanguageId");

                    b.ToTable("Developer");

                    b.HasData(
                        new
                        {
                            DeveloperId = 1,
                            FirstName = "John",
                            Gender = "Male",
                            LastName = "Smith",
                            Level = "Junior",
                            PrimaryLanguageId = 1,
                            YearsOfExperience = 1
                        },
                        new
                        {
                            DeveloperId = 2,
                            FirstName = "Joe",
                            Gender = "Male",
                            LastName = "Dou",
                            Level = "JuniorPro",
                            PrimaryLanguageId = 2,
                            YearsOfExperience = 2
                        },
                        new
                        {
                            DeveloperId = 3,
                            FirstName = "Tom",
                            Gender = "Male",
                            LastName = "Stack",
                            Level = "Indermediate",
                            PrimaryLanguageId = 3,
                            YearsOfExperience = 3
                        },
                        new
                        {
                            DeveloperId = 4,
                            FirstName = "Stepan",
                            Gender = "Male",
                            LastName = "Zayats",
                            Level = "IntermediatePro",
                            PrimaryLanguageId = 4,
                            YearsOfExperience = 4
                        },
                        new
                        {
                            DeveloperId = 5,
                            FirstName = "Petro",
                            Gender = "Male",
                            LastName = "Vovk",
                            Level = "Senior",
                            PrimaryLanguageId = 5,
                            YearsOfExperience = 5
                        },
                        new
                        {
                            DeveloperId = 6,
                            FirstName = "Vasyl",
                            Gender = "Male",
                            LastName = "Door",
                            Level = "SeniorPro",
                            PrimaryLanguageId = 6,
                            YearsOfExperience = 6
                        },
                        new
                        {
                            DeveloperId = 7,
                            FirstName = "Brian",
                            Gender = "Male",
                            LastName = "Laptop",
                            Level = "TechLead",
                            PrimaryLanguageId = 1,
                            YearsOfExperience = 8
                        },
                        new
                        {
                            DeveloperId = 8,
                            FirstName = "Ivan",
                            Gender = "Male",
                            LastName = "Table",
                            Level = "Architect",
                            PrimaryLanguageId = 1,
                            YearsOfExperience = 10
                        },
                        new
                        {
                            DeveloperId = 9,
                            FirstName = "Dmytro",
                            Gender = "Male",
                            LastName = "Glass",
                            Level = "Senior",
                            PrimaryLanguageId = 1,
                            YearsOfExperience = 3
                        },
                        new
                        {
                            DeveloperId = 10,
                            FirstName = "Hrytsko",
                            Gender = "Male",
                            LastName = "Wall",
                            Level = "SeniorPro",
                            PrimaryLanguageId = 1,
                            YearsOfExperience = 4
                        },
                        new
                        {
                            DeveloperId = 11,
                            FirstName = "Viktor",
                            Gender = "Male",
                            LastName = "Window",
                            Level = "Indermediate",
                            PrimaryLanguageId = 1,
                            YearsOfExperience = 2
                        },
                        new
                        {
                            DeveloperId = 12,
                            FirstName = "Hnat",
                            Gender = "Male",
                            LastName = "Refrig",
                            Level = "IntermediatePro",
                            PrimaryLanguageId = 1,
                            YearsOfExperience = 6
                        },
                        new
                        {
                            DeveloperId = 13,
                            FirstName = "Zahar",
                            Gender = "Male",
                            LastName = "Vedmid",
                            Level = "TechLead",
                            PrimaryLanguageId = 1,
                            YearsOfExperience = 19
                        },
                        new
                        {
                            DeveloperId = 14,
                            FirstName = "Kyrylo",
                            Gender = "Male",
                            LastName = "Lys",
                            Level = "TechLeadPro",
                            PrimaryLanguageId = 1,
                            YearsOfExperience = 8
                        },
                        new
                        {
                            DeveloperId = 15,
                            FirstName = "Mykola",
                            Gender = "Male",
                            LastName = "Oven",
                            Level = "JuniorPro",
                            PrimaryLanguageId = 1,
                            YearsOfExperience = 13
                        },
                        new
                        {
                            DeveloperId = 16,
                            FirstName = "Orest",
                            Gender = "Male",
                            LastName = "Camer",
                            Level = "Junior",
                            PrimaryLanguageId = 1,
                            YearsOfExperience = 1
                        },
                        new
                        {
                            DeveloperId = 17,
                            FirstName = "Ostap",
                            Gender = "Male",
                            LastName = "Monit",
                            Level = "Senior",
                            PrimaryLanguageId = 2,
                            YearsOfExperience = 14
                        },
                        new
                        {
                            DeveloperId = 18,
                            FirstName = "Roman",
                            Gender = "Male",
                            LastName = "Noran",
                            Level = "Senior",
                            PrimaryLanguageId = 3,
                            YearsOfExperience = 4
                        },
                        new
                        {
                            DeveloperId = 19,
                            FirstName = "Svyatohor",
                            Gender = "Male",
                            LastName = "Velykyy",
                            Level = "Senior",
                            PrimaryLanguageId = 4,
                            YearsOfExperience = 8
                        },
                        new
                        {
                            DeveloperId = 20,
                            FirstName = "Taras",
                            Gender = "Male",
                            LastName = "Bulba",
                            Level = "Senior",
                            PrimaryLanguageId = 5,
                            YearsOfExperience = 6
                        },
                        new
                        {
                            DeveloperId = 21,
                            FirstName = "Yuliy",
                            Gender = "Male",
                            LastName = "Cesar",
                            Level = "Senior",
                            PrimaryLanguageId = 6,
                            YearsOfExperience = 9
                        },
                        new
                        {
                            DeveloperId = 22,
                            FirstName = "Yakiv",
                            Gender = "Male",
                            LastName = "Spurt",
                            Level = "Indermediate",
                            PrimaryLanguageId = 2,
                            YearsOfExperience = 1
                        },
                        new
                        {
                            DeveloperId = 23,
                            FirstName = "Yarema",
                            Gender = "Male",
                            LastName = "Tras",
                            Level = "TechLead",
                            PrimaryLanguageId = 6,
                            YearsOfExperience = 1
                        },
                        new
                        {
                            DeveloperId = 24,
                            FirstName = "Barbara",
                            Gender = "Female",
                            LastName = "Chair",
                            Level = "Junior",
                            PrimaryLanguageId = 1,
                            YearsOfExperience = 2
                        },
                        new
                        {
                            DeveloperId = 25,
                            FirstName = "Sarah",
                            Gender = "Female",
                            LastName = "Wash",
                            Level = "Indermediate",
                            PrimaryLanguageId = 6,
                            YearsOfExperience = 4
                        },
                        new
                        {
                            DeveloperId = 26,
                            FirstName = "Viktoria",
                            Gender = "Female",
                            LastName = "Mach",
                            Level = "IntermediatePro",
                            PrimaryLanguageId = 6,
                            YearsOfExperience = 6
                        },
                        new
                        {
                            DeveloperId = 27,
                            FirstName = "Hanna",
                            Gender = "Female",
                            LastName = "Pone",
                            Level = "Senior",
                            PrimaryLanguageId = 6,
                            YearsOfExperience = 8
                        },
                        new
                        {
                            DeveloperId = 28,
                            FirstName = "Daryna",
                            Gender = "Female",
                            LastName = "Cell",
                            Level = "JuniorPro",
                            PrimaryLanguageId = 2,
                            YearsOfExperience = 2
                        },
                        new
                        {
                            DeveloperId = 29,
                            FirstName = "Erika",
                            Gender = "Female",
                            LastName = "Shoe",
                            Level = "Junior",
                            PrimaryLanguageId = 2,
                            YearsOfExperience = 4
                        },
                        new
                        {
                            DeveloperId = 30,
                            FirstName = "Yevdokiya",
                            Gender = "Female",
                            LastName = "Switch",
                            Level = "JuniorPro",
                            PrimaryLanguageId = 1,
                            YearsOfExperience = 3
                        });
                });

            modelBuilder.Entity("IdealWay.Domain.Entities.ProgrammingLanguage", b =>
                {
                    b.Property<int>("ProgrammingLanguageId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsStronglyTyped");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("ProgrammingLanguageId");

                    b.ToTable("ProgrammingLanguage");

                    b.HasData(
                        new
                        {
                            ProgrammingLanguageId = 1,
                            IsStronglyTyped = true,
                            Name = "C#"
                        },
                        new
                        {
                            ProgrammingLanguageId = 2,
                            IsStronglyTyped = true,
                            Name = "Java"
                        },
                        new
                        {
                            ProgrammingLanguageId = 3,
                            IsStronglyTyped = false,
                            Name = "C"
                        },
                        new
                        {
                            ProgrammingLanguageId = 4,
                            IsStronglyTyped = true,
                            Name = "Python"
                        },
                        new
                        {
                            ProgrammingLanguageId = 5,
                            IsStronglyTyped = false,
                            Name = "C++"
                        },
                        new
                        {
                            ProgrammingLanguageId = 6,
                            IsStronglyTyped = false,
                            Name = "JavaScript"
                        });
                });

            modelBuilder.Entity("IdealWay.Domain.Entities.SurveyAnswer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeveloperId");

                    b.Property<bool>("Satisfied")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<int>("YearSalary");

                    b.HasKey("AnswerId");

                    b.HasIndex("DeveloperId");

                    b.ToTable("SurveyAnswer");

                    b.HasData(
                        new
                        {
                            AnswerId = 1,
                            DeveloperId = 1,
                            Satisfied = false,
                            YearSalary = 43000
                        },
                        new
                        {
                            AnswerId = 2,
                            DeveloperId = 2,
                            Satisfied = true,
                            YearSalary = 50000
                        },
                        new
                        {
                            AnswerId = 3,
                            DeveloperId = 3,
                            Satisfied = false,
                            YearSalary = 49000
                        },
                        new
                        {
                            AnswerId = 4,
                            DeveloperId = 4,
                            Satisfied = false,
                            YearSalary = 52000
                        },
                        new
                        {
                            AnswerId = 5,
                            DeveloperId = 5,
                            Satisfied = false,
                            YearSalary = 55000
                        },
                        new
                        {
                            AnswerId = 6,
                            DeveloperId = 6,
                            Satisfied = false,
                            YearSalary = 58000
                        },
                        new
                        {
                            AnswerId = 7,
                            DeveloperId = 7,
                            Satisfied = true,
                            YearSalary = 75000
                        },
                        new
                        {
                            AnswerId = 8,
                            DeveloperId = 8,
                            Satisfied = true,
                            YearSalary = 85000
                        },
                        new
                        {
                            AnswerId = 9,
                            DeveloperId = 9,
                            Satisfied = false,
                            YearSalary = 55000
                        },
                        new
                        {
                            AnswerId = 10,
                            DeveloperId = 10,
                            Satisfied = false,
                            YearSalary = 58000
                        },
                        new
                        {
                            AnswerId = 11,
                            DeveloperId = 11,
                            Satisfied = true,
                            YearSalary = 55000
                        },
                        new
                        {
                            AnswerId = 12,
                            DeveloperId = 12,
                            Satisfied = false,
                            YearSalary = 52000
                        },
                        new
                        {
                            AnswerId = 13,
                            DeveloperId = 13,
                            Satisfied = false,
                            YearSalary = 61000
                        },
                        new
                        {
                            AnswerId = 14,
                            DeveloperId = 14,
                            Satisfied = false,
                            YearSalary = 64000
                        },
                        new
                        {
                            AnswerId = 15,
                            DeveloperId = 15,
                            Satisfied = false,
                            YearSalary = 46000
                        },
                        new
                        {
                            AnswerId = 16,
                            DeveloperId = 16,
                            Satisfied = false,
                            YearSalary = 43000
                        },
                        new
                        {
                            AnswerId = 17,
                            DeveloperId = 17,
                            Satisfied = false,
                            YearSalary = 55000
                        },
                        new
                        {
                            AnswerId = 18,
                            DeveloperId = 18,
                            Satisfied = true,
                            YearSalary = 65000
                        },
                        new
                        {
                            AnswerId = 19,
                            DeveloperId = 19,
                            Satisfied = false,
                            YearSalary = 55000
                        },
                        new
                        {
                            AnswerId = 20,
                            DeveloperId = 20,
                            Satisfied = true,
                            YearSalary = 65000
                        },
                        new
                        {
                            AnswerId = 21,
                            DeveloperId = 21,
                            Satisfied = false,
                            YearSalary = 55000
                        },
                        new
                        {
                            AnswerId = 22,
                            DeveloperId = 22,
                            Satisfied = true,
                            YearSalary = 55000
                        },
                        new
                        {
                            AnswerId = 23,
                            DeveloperId = 23,
                            Satisfied = false,
                            YearSalary = 61000
                        },
                        new
                        {
                            AnswerId = 24,
                            DeveloperId = 24,
                            Satisfied = false,
                            YearSalary = 43000
                        },
                        new
                        {
                            AnswerId = 25,
                            DeveloperId = 25,
                            Satisfied = true,
                            YearSalary = 55000
                        },
                        new
                        {
                            AnswerId = 26,
                            DeveloperId = 26,
                            Satisfied = false,
                            YearSalary = 52000
                        },
                        new
                        {
                            AnswerId = 27,
                            DeveloperId = 27,
                            Satisfied = false,
                            YearSalary = 55000
                        },
                        new
                        {
                            AnswerId = 28,
                            DeveloperId = 28,
                            Satisfied = true,
                            YearSalary = 50000
                        },
                        new
                        {
                            AnswerId = 29,
                            DeveloperId = 29,
                            Satisfied = true,
                            YearSalary = 45000
                        },
                        new
                        {
                            AnswerId = 30,
                            DeveloperId = 30,
                            Satisfied = false,
                            YearSalary = 46000
                        });
                });

            modelBuilder.Entity("IdealWay.Domain.Entities.Developer", b =>
                {
                    b.HasOne("IdealWay.Domain.Entities.ProgrammingLanguage", "PrimaryLanguage")
                        .WithMany("Developers")
                        .HasForeignKey("PrimaryLanguageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IdealWay.Domain.Entities.SurveyAnswer", b =>
                {
                    b.HasOne("IdealWay.Domain.Entities.Developer", "Developer")
                        .WithMany("Answers")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
